# Copyright 2026 AgentMindCloud
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
"""Shared fixtures for hypothesis property-based tests against the v2.15
manifest schema.

Built for xAI, X, Grok and the ecosystem community.

Why this file exists
--------------------
P179 (snapshot + property tests) catches the silent prompt-version drift
failure mode that produced the SEPOS routing bug. The strategy here
generates *valid* v2.15 manifest dicts (so we can prove the Pydantic model
accepts them) and *deliberately broken* mutations (so we can prove the
model rejects them with a ValidationError). All work is hermetic: no
network, no secrets, no Windows-only code paths.

The session-scoped ``grok_agent_module`` fixture imports the CLI module
(``cli/grok-agent.py``) by file path because the filename is not a valid
Python identifier. We then call ``GrokAgentManifest.model_rebuild`` with
the module's namespace so Pydantic resolves the forward references that
``from __future__ import annotations`` left behind. This mirrors the
pattern already used by ``scripts/export-openapi.py``.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, Callable

import pytest

# Skip cleanly if hypothesis is not available — the test files themselves
# also call importorskip, so the suite degrades gracefully on minimal
# installs (e.g. fresh GitHub Codespaces before `pip install -e .[dev]`).
hypothesis = pytest.importorskip("hypothesis")
st = pytest.importorskip("hypothesis.strategies")


_REPO_ROOT = Path(__file__).resolve().parents[2]
_CLI_MODULE_PATH = _REPO_ROOT / "cli" / "grok-agent.py"


# Mirror cli/grok-agent.py KIND_VALUES exactly. Listed explicitly (not
# imported) so a typo in the CLI surfaces as a test failure rather than
# silently dragging the test along.
_KIND_VALUES: tuple[str, ...] = (
    "agent",
    "finance-dashboard",
    "alpha-engine",
    "creator-payout-optimizer",
    "vision-analyzer",
    "super-agent",
    "x-native",
    "creator-template",
)


# A name-pattern strategy that matches r"^[a-z][a-z0-9-]*$" and stays short
# so each generated example builds in well under a millisecond.
def _name_strategy() -> Any:
    head = st.sampled_from(list("abcdefghijklmnopqrstuvwxyz"))
    rest = st.text(
        alphabet=st.sampled_from(list("abcdefghijklmnopqrstuvwxyz0123456789-")),
        min_size=0,
        max_size=24,
    )
    return st.builds(lambda h, t: h + t, head, rest)


def _description_strategy() -> Any:
    # Pydantic enforces min_length=10 — we generate 10..120 ASCII printable
    # chars (no control chars, no surrogates) so each example is small and
    # deterministic.
    safe_alphabet = st.sampled_from(
        list(
            "abcdefghijklmnopqrstuvwxyz"
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "0123456789"
            " .,-_:;!?()"
        )
    )
    return st.text(alphabet=safe_alphabet, min_size=10, max_size=120)


def _author_strategy() -> Any:
    safe_alphabet = st.sampled_from(
        list(
            "abcdefghijklmnopqrstuvwxyz"
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "0123456789 -_."
        )
    )
    return st.text(alphabet=safe_alphabet, min_size=1, max_size=48)


@pytest.fixture(scope="session")
def grok_agent_module() -> Any:
    """Import cli/grok-agent.py by file path and call model_rebuild.

    Returns the live module object so callers can pull
    ``GrokAgentManifest`` (and constants like ``ACCEPTED_VERSIONS``) off
    it. Cached for the whole session — the module load is not free.
    """
    if not _CLI_MODULE_PATH.exists():
        pytest.skip(f"CLI module missing at {_CLI_MODULE_PATH}")

    spec = importlib.util.spec_from_file_location(
        "grok_agent_cli_for_property_tests", _CLI_MODULE_PATH
    )
    if spec is None or spec.loader is None:
        pytest.skip(f"Could not load CLI module at {_CLI_MODULE_PATH}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    # Resolve forward references left behind by `from __future__ import
    # annotations` in cli/grok-agent.py.
    module.GrokAgentManifest.model_rebuild(_types_namespace=vars(module))
    return module


@pytest.fixture(scope="session")
def grok_agent_manifest_cls(grok_agent_module: Any) -> Any:
    """Convenience alias — returns the rebuilt GrokAgentManifest class."""
    return grok_agent_module.GrokAgentManifest


def _build_valid_manifest_strategy() -> Any:
    """Hypothesis strategy that returns dicts conforming to v2.15.

    Every dict generated by this strategy is a *minimal* valid manifest:
    only the six required top-level fields plus a constitution stub when
    kind=='super-agent' and a grok stub when kind=='vision-analyzer'.
    The two extra stubs satisfy the ``_kind_consistency`` model validator
    in cli/grok-agent.py so we never trip a kind-specific rule.
    """
    return st.fixed_dictionaries(
        {
            "version": st.sampled_from(["2.14", "2.15"]),
            "kind": st.sampled_from(list(_KIND_VALUES)),
            "name": _name_strategy(),
            "description": _description_strategy(),
            "author": _author_strategy(),
            "license": st.just("Apache-2.0"),
        }
    ).map(_apply_kind_required_blocks)


def _apply_kind_required_blocks(d: dict) -> dict:
    """Add the kind-specific required nested blocks the model demands.

    - super-agent → constitution: { ... } stub
    - vision-analyzer → grok: { vision: True } stub
    """
    out = dict(d)
    if out["kind"] == "super-agent":
        # Constitution shape comes from cli/grok-agent.py — `rules` is the
        # required field (min_length=1); the other two lists are optional
        # but listed for clarity.
        out["constitution"] = {
            "rules": ["honesty"],
            "consent_gates": ["read", "write"],
            "hard_refusals": [
                "I will not do that without explicit consent."
            ],
        }
    if out["kind"] == "vision-analyzer":
        out["grok"] = {
            "model": "grok-4.3",
            "vision": True,
        }
    return out


@pytest.fixture(scope="session")
def valid_manifest_strategy() -> Any:
    """Hypothesis strategy producing valid v2.15 manifest dicts."""
    return _build_valid_manifest_strategy()


# Mutation registry — each entry is a (label, callable) pair. The callable
# takes a valid manifest dict and returns a *broken* copy with exactly one
# field error. Listed explicitly so a hypothesis failure tells us which
# rule was being exercised.
def _mutation_drop_version(d: dict) -> dict:
    out = dict(d)
    out.pop("version", None)
    return out


def _mutation_bad_version(d: dict) -> dict:
    out = dict(d)
    out["version"] = "1.0"  # not in ACCEPTED_VERSIONS
    return out


def _mutation_bad_kind(d: dict) -> dict:
    out = dict(d)
    out["kind"] = "definitely-not-a-real-kind"
    return out


def _mutation_bad_name(d: dict) -> dict:
    out = dict(d)
    out["name"] = "9starts-with-digit"  # violates ^[a-z][a-z0-9-]*$
    return out


def _mutation_short_description(d: dict) -> dict:
    out = dict(d)
    out["description"] = "short"  # < 10 chars
    return out


def _mutation_empty_author(d: dict) -> dict:
    out = dict(d)
    out["author"] = ""  # min_length=1 fails
    return out


def _mutation_bad_license(d: dict) -> dict:
    out = dict(d)
    out["license"] = "MIT"  # only Apache-2.0 is accepted
    return out


_MUTATIONS: tuple[tuple[str, Callable[[dict], dict]], ...] = (
    ("drop-version", _mutation_drop_version),
    ("bad-version", _mutation_bad_version),
    ("bad-kind", _mutation_bad_kind),
    ("bad-name", _mutation_bad_name),
    ("short-description", _mutation_short_description),
    ("empty-author", _mutation_empty_author),
    ("bad-license", _mutation_bad_license),
)


@pytest.fixture(scope="session")
def invalid_manifest_strategy(valid_manifest_strategy: Any) -> Any:
    """Hypothesis strategy producing manifests with exactly one field error.

    Each draw picks a valid manifest and a mutation function from the
    enumerated registry above. The result is always a dict the v2.15
    Pydantic model must reject.
    """

    def _mutate(pair: tuple[dict, tuple[str, Callable[[dict], dict]]]) -> dict:
        valid, (_label, mutate) = pair
        return mutate(valid)

    pairs = st.tuples(valid_manifest_strategy, st.sampled_from(list(_MUTATIONS)))
    return pairs.map(_mutate)
