/**
 * Copyright 2026 AgentMindCloud
 * Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */

// Build-time YAML → typed Agent loader.
// Reads content/agents.json (generated by scripts/build-agents-index.ts).
// Falls back to lib/manifests.ts scanner when the JSON is missing.

import type { Agent } from './types';

// TODO: import from content/agents.json once prebuild is wired
export function loadAgents(): Agent[] {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { loadAllAgents } = require('./manifests') as typeof import('./manifests');
  return loadAllAgents();
}
