// Copyright 2026 AgentMindCloud
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// Form helpers for the /deploy route. Pure client-safe logic — slugify,
// validate, generate v2.15 YAML, build deep-links and X share URLs.
// Imports types from lib/types.ts so the deploy form does not pull in
// the server-only manifest scanner.

import {
  DEFAULT_CONSENT_GATES,
  DEFAULT_PORT_FOR_KIND,
  DeployFormInput,
  KIND_HELPER,
  MANIFEST_KIND_OPTIONS,
  ManifestKind,
  ValidationResult,
} from './types';

export type { DeployFormInput, ManifestKind, ValidationResult } from './types';
export {
  DEFAULT_CONSENT_GATES,
  DEFAULT_PORT_FOR_KIND,
  KIND_HELPER,
  MANIFEST_KIND_OPTIONS,
} from './types';

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');
}

interface DeployToXOptions {
  slug: string;
  description: string;
  pageUrl: string;
  attribution?: boolean;
}

export function buildDeployToXUrl(opts: DeployToXOptions): string {
  const lines = [
    'grok install this',
    '',
    opts.description,
    '',
    opts.pageUrl,
  ];
  if (opts.attribution) {
    lines.push('', 'Manifest generated via the Grok Agent OS marketplace.');
  }
  const text = lines.join('\n');
  const url = new URL('https://x.com/intent/post');
  url.searchParams.set('text', text);
  return url.toString();
}

export function buildDeepLink(input: DeployFormInput): string {
  const params = new URLSearchParams();
  params.set('name', input.name);
  params.set('kind', input.kind);
  params.set('description', input.description);
  params.set('author', input.author);
  params.set('port', String(input.defaultPort));
  params.set('gates', input.consentGates.join(','));
  params.set('rtx', input.realTimeX ? '1' : '0');
  return `/deploy?${params.toString()}`;
}

const NAME_PATTERN = /^[a-z][a-z0-9-]*$/;

export function validateDeployInput(input: DeployFormInput): ValidationResult {
  const fields: ValidationResult['fields'] = {};
  const errors: string[] = [];

  if (!input.name) {
    fields.name = 'Name is required.';
    errors.push('Name is required.');
  } else if (!NAME_PATTERN.test(input.name)) {
    fields.name = 'Name must be kebab-case (a-z, 0-9, hyphens).';
    errors.push('Name must be kebab-case.');
  }

  if (!MANIFEST_KIND_OPTIONS.includes(input.kind)) {
    fields.kind = 'Pick a valid kind.';
    errors.push('Kind must be one of the v2.15 enum values.');
  }

  if (!input.description || input.description.length < 12) {
    fields.description = 'Description must be at least 12 characters.';
    errors.push('Description too short (min 12 chars).');
  } else if (input.description.length > 280) {
    fields.description = 'Description must be 280 characters or fewer.';
    errors.push('Description too long (max 280 chars).');
  }

  if (!input.author || !/^@[A-Za-z0-9_]{1,15}$/.test(input.author.trim())) {
    fields.author = 'Author must be an X handle starting with @.';
    errors.push('Author must be an X handle starting with @.');
  }

  if (
    !Number.isInteger(input.defaultPort) ||
    input.defaultPort < 1024 ||
    input.defaultPort > 65535
  ) {
    fields.defaultPort = 'Port must be an integer between 1024 and 65535.';
    errors.push('Port out of range.');
  }

  for (const gate of input.consentGates) {
    if (!/^[a-z][a-z0-9_]*$/.test(gate)) {
      fields.consentGates = `Consent gate "${gate}" must be snake_case.`;
      errors.push(`Consent gate "${gate}" must be snake_case.`);
      break;
    }
  }

  return { ok: errors.length === 0, errors, fields };
}

function yamlList(items: string[], spaces: number): string {
  if (items.length === 0) return '[]';
  const pad = ' '.repeat(spaces);
  return '\n' + items.map((item) => `${pad}- "${item}"`).join('\n');
}

export function generateManifestYaml(input: DeployFormInput): string {
  const headerLines = [
    '# Apache 2.0 License',
    '# Copyright 2026 AgentMindCloud',
    '#',
    '# Generated by the Grok Agent OS marketplace deploy form.',
    '# Validate with: python cli/grok-agent.py validate grok-agent.yaml',
  ];

  const body: string[] = [];
  body.push(`version: "2.15"`);
  body.push(`kind: "${input.kind}"`);
  body.push(`name: "${input.name}"`);
  body.push(`description: "${input.description.replace(/"/g, '\\"')}"`);
  body.push(`author: "${input.author}"`);
  body.push(`license: "Apache-2.0"`);
  body.push('');
  body.push('install:');
  body.push('  one_click: true');
  body.push(`  install_command: "grok-agent install ${input.name}"`);
  body.push('');
  body.push('windows:');
  body.push('  launcher: "launcher.ps1"');
  body.push(`  default_port: ${input.defaultPort}`);
  body.push('  chrome_only: true');
  body.push('  requires_admin: false');
  body.push('');
  body.push('safety:');
  body.push('  pii_handling: "local-only"');
  body.push('  data_retention_days: 90');
  body.push('  scanner_severity_floor: "warn"');

  const gates = input.consentGates.length > 0 ? input.consentGates : ['none'];
  body.push('');
  body.push('constitution:');
  body.push(`  consent_gates:${yamlList(gates, 4)}`);

  if (input.realTimeX) {
    body.push('');
    body.push('real_time_x:');
    body.push('  enabled: true');
    body.push('  reply_only: true');
    body.push('  consent_required: true');
  }

  return headerLines.join('\n') + '\n\n' + body.join('\n') + '\n';
}
